name: Actualizar CSV desde Google Sheets

permissions:
  contents: write  # importante para poder hacer push

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Descargar CSV
        run: curl -L -o data.csv "https://docs.google.com/spreadsheets/d/1pjtykzqGhaTkVfTNK7RsHHuu_u67hiA3jEsn0uMPLFY/export?format=csv&gid=223702133"

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit y push si hay cambios
        run: |
          git add *.csv
          git diff --cached --quiet || git commit -m "Actualizar CSV desde Google Sheets"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ManuUBA/Horarios-zero.git HEAD:main
